# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "parallels/debian-8.2"
    config.vm.hostname = "database.app"

    config.vm.network :private_network, ip: "192.168.100.5"
    config.vm.network "forwarded_port", guest: 3306, host: 3306
    config.vm.provision :shell, :path => "install.sh"

end
