# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "parallels/debian-8.2"
  config.vm.hostname = "php7.app"

  # config.vm.network "forwarded_port", guest: 8080, host: 80
  config.vm.network "private_network", ip: "192.168.100.70"

  config.vm.synced_folder "/Volumes/sources", "/sources", owner: "www-data", group: "www-data"
  config.vm.synced_folder "./../build", "/build"

  config.ssh.forward_agent = true

  config.vm.provision :shell, :path => "install.sh"
end